### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by dceejay** [bloigge/node-red-contrib-turf#1]
Not an issue - just the easiest way to say Hi. 
thanks for the node - looks really interesting.
We have several nodes that produce or accept geo info - mainly on `msg.payload.lat` and `msg.payload.lon` or sometimes `msg.lat`  and `msg.lon`  - It may be good to also create a simple parse node that looks for these and converts to geoJSON if possible and vice versa ?
Also you may wish to change the category of the node to "location" so it sits alongside the geofence node for example...
But thanks !

**Comment by bloigge** [comment]
Hi @dceejay .
Thanks for the feedback. I changed the category to location. 
I am interested in everything that has to do with geo- / GIS-related stuff. The only geo-related node I found is  "node-red-node-geofence" - could you send me the names of other geo nodes? Btw: is there a way to filter the nodes by category on http://flows.nodered.org/ ? 

A  parse node would be easy to develop I guess. I'll give it a shot this week.

**Comment by dceejay** [comment]
Some of the weather nodes and web nodes have a location component - I think all are buried in here (though they are published as separate nodes) - though it must be said some of the non-weather ones have not been touched for a while so the backend APIs may have changed / broken them.
https://github.com/node-red/node-red-web-nodes

**Comment by bloigge** [comment]
@dceejay - I checked some of your nodes. It seems that there is always a msg.location object with the coordinates. Using turf there is already a function, that takes lat/long as input and creates a geojson:

Example using your instagram node:
`[{"id":"66b019d4.488ac8","type":"instagram","z":"2902b32a.d6fd4c","instagram":"","inputType":"photo","outputType":"link","name":"","x":329,"y":723,"wires":[["c979414d.6ffed"]]},{"id":"fb66dfdc.a461c","type":"inject","z":"2902b32a.d6fd4c","name":"Create GeoJson","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":154,"y":723,"wires":[["66b019d4.488ac8"]]},{"id":"3314a401.148ffc","type":"turf","z":"2902b32a.d6fd4c","name":"createGeoJson","x":656,"y":724,"wires":[["95460886.21fe98"]]},{"id":"c979414d.6ffed","type":"function","z":"2902b32a.d6fd4c","name":"","func":"msg.topic = \"point\";\nmsg.payload = [[msg.location.lat, msg.location.lon]];\nreturn msg;","outputs":1,"noerr":0,"x":483,"y":724,"wires":[["3314a401.148ffc"]]},{"id":"95460886.21fe98","type":"debug","z":"2902b32a.d6fd4c","name":"","active":true,"console":"false","complete":"false","x":840,"y":725,"wires":[]}]`

The other way round is even more easy, because if you have a geojson point feature as your output the coordinates are in the coordinates array:

Example for reading lat/long from GeoJson, finding a center point from a FeatureCollection and using wonderground:
`[{"id":"f48eca4e.ffb018","type":"wunderground","z":"2902b32a.d6fd4c","name":"","lon":"","lat":"","city":"","country":"","x":815,"y":569,"wires":[["b396cc54.7c7b9"]]},{"id":"5f270b86.8d1c64","type":"inject","z":"2902b32a.d6fd4c","name":"Use GeoJson","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":105,"y":629,"wires":[["66fa7563.c2ce6c"]]},{"id":"577be011.43e75","type":"turf","z":"2902b32a.d6fd4c","name":"create random points","x":173,"y":570,"wires":[["3b0b617.926ba9e"]]},{"id":"66fa7563.c2ce6c","type":"function","z":"2902b32a.d6fd4c","name":"","func":"msg.topic = \"random\";\nmsg.payload = ['polygons', 100, {\n  bbox: [-70, 40, -60, 60]\n}];\nreturn msg;","outputs":1,"noerr":0,"x":252,"y":630,"wires":[["577be011.43e75"]]},{"id":"3b0b617.926ba9e","type":"function","z":"2902b32a.d6fd4c","name":"","func":"msg.topic = \"center\";\nmsg.payload = [msg.payload];\nreturn msg;","outputs":1,"noerr":0,"x":332,"y":570,"wires":[["ee74b31c.c2416"]]},{"id":"ee74b31c.c2416","type":"turf","z":"2902b32a.d6fd4c","name":"find center","x":478,"y":570,"wires":[["20a115ba.45cd6a"]]},{"id":"20a115ba.45cd6a","type":"function","z":"2902b32a.d6fd4c","name":"","func":"msg.location = {};\nmsg.location.lat = msg.payload.geometry.coordinates[1];\nmsg.location.lon = msg.payload.geometry.coordinates[0];\nreturn msg;","outputs":1,"noerr":0,"x":632,"y":571,"wires":[["f48eca4e.ffb018"]]},{"id":"b396cc54.7c7b9","type":"debug","z":"2902b32a.d6fd4c","name":"","active":true,"console":"false","complete":"false","x":1009,"y":570,"wires":[]}]`

Hope that helps and Happy Easter!
